### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by oparisy** [chrischristo/capsule-maven-plugin#16]
Hi, I am using maven to build a small program depending on `org.lwjgl.lwjgl:lwjgl:2.9.1`.

Up to now, I have been using `maven-nativedependencies-plugin` to unpack the native libraries provided by `lwjgl`, and have been able to run my code sucessfully using `-Djava.library.path=target/natives`, [as suggested here](http://dev-stuffs.blogspot.fr/2013/04/lwjgl-maven-and-eclipse.html).

I would now like to build a fat capsule, which would enable me to run my program without specifying `-Djava.library.path` on the command line. What should I do for this purpose?

For now:
- The capsule properly embarks at its root the jars containing the native libraries (`lwjgl-platform-2.9.1-natives-windows.jar` as an example, which contains `lwjgl.dll`).
- I get an `UnsatisfiedLinkError: no lwjgl in java.library.path` when running the jar.

Here is the relevant POM fragment:

```
            <plugin>
                <groupId>com.github.chrischristo</groupId>
                <artifactId>capsule-maven-plugin</artifactId>
                <version>0.10.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                        </goals>
                        <configuration>
                            <appClass>org.lwjgl.examples.spaceinvaders.Game</appClass>
                            <types>fat</types>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by chrischristo** [comment]
Hmm ok thanks for letting me know, will look into this.
