### ISSUE TITLE
Allow capsule JARs to be renamed

### ISSUE THREAD

**Issue by fbiville** [chrischristo/capsule-maven-plugin#17]
Hi, I'm in the context when I'm producing only 1 JAR and I would like to be able to configure its name. It seems to me this is not possible in the current version.

**Comment by chrischristo** [comment]
Hi, well what you can do is add the maven tag `<finalName>` within the `<build>` tag so for example:

```
<build>
  <finalName>my-custom-name</finalName>
  <plugins>
  ...
  </plugins>
</build>
```

which will change the name of the output jars to the following:

```
my-custom-name-capsule-empty.jar
my-custom-name-capsule-fat.jar
my-custom-name-capsule-thin.jar

my-custom-name-capsule-empty.x
my-custom-name-capsule-fat.x
my-custom-name-capsule-thin.x
```

Note that this method only changes the first part of the name of the output jars. The plugin will always append the part `-capsule-[type].[ext]` at the end.

Is this ok? or did you want to change the whole name including the extension?

**Comment by fbiville** [comment]
Yep, I wanted to change the whole name (and ended up with `maven-antrun-plugin` for that.
This is especially useful when configuring only 1 type of capsule.

**Comment by chrischristo** [comment]
Hey, just added support for this in v0.10.1, see info about it [here](https://github.com/chrischristo/capsule-maven-plugin#custom-file-names).

**Comment by fbiville** [comment]
:+1: thanks :)
