### ISSUE TITLE
Leaving capsule.version unspecified *currently* resolves to an unstable snapshot

### ISSUE THREAD

**Issue by chrisfjones** [chrischristo/capsule-maven-plugin#18]
I came across the following issue when trying to build a new capsule project:
https://github.com/puniverse/capsule/issues/55
This came up because my project (using capsule-maven-plugin v0.10.0) was resolving the latest capsule version (which happened to be 1.0-rc1-SNAPSHOT and contained the bug above).
Ideally, capsule-maven-plugin would ignore '*-SNAPSHOT' capsule versions when resolving the 'latest' capsule version.
I've been able to work around this issue by explicitly setting capsule.version:
<capsule.version>0.10.0</capsule.version>

**Comment by chrischristo** [comment]
Ah yeah you're right, thanks for reporting. Will issue a fix.

**Comment by chrischristo** [comment]
This is actually a bug in the way VersionRangeRequest (incorrectly) works - see [here](https://jira.codehaus.org/browse/MNG-3092). 

In any case, I've managed to write additional code to skip the SNAPSHOT version and find the latest non-snapshot version. [Resolved in 0.10.3](https://github.com/chrischristo/capsule-maven-plugin/releases/tag/capsule-maven-plugin-0.10.3)
