### ISSUE TITLE
Custom capsule name bug

### ISSUE THREAD

**Issue by nilsga** [chrischristo/capsule-maven-plugin#19]
Seems like the generated file name of the capsule is incorrect. Instead of `<finalName>-<descriptorName>.jar`, the result is `<finalName><finalName>-<descriptorName>.jar`.

**Comment by chrischristo** [comment]
thanks for reporting! fixed in [0.10.2](https://github.com/chrischristo/capsule-maven-plugin/releases/tag/capsule-maven-plugin-0.10.2). Releasing it on maven central now (give it an hour or two).
