### ISSUE TITLE
Multi-module maven projects should include specified sibling modules artifacts in thin jars

### ISSUE THREAD

**Issue by btiernay** [chrischristo/capsule-maven-plugin#20]
In many scenarios, a multi-module maven build will be deployed as a unit (ex. SNAPSHOT builds that share a common version), but are decomposed for "static modularity". In some cases, these artifacts may need special packing themselves (e.g. shade class relocation). For this reason, it would be extremely useful to add the ability to add their primary artifact to the contents of the thin jar.

**Comment by chrischristo** [comment]
Can you explain further what it is exactly you would like?

**Comment by chrischristo** [comment]
Please let me know how I can assist you, otherwise I will close due to inactivity.
