### ISSUE TITLE
Should register artifacts for mvn install and mvn deploy or update documentation

### ISSUE THREAD

**Issue by tngmech** [chrischristo/capsule-maven-plugin#23]
When following the documentation https://github.com/chrischristo/capsule-maven-plugin to include the plugin during builds the plugin creates e.g. the capsule-fat.jar into the target folder as expected. However the e.g. capsule-fat.jar artifact will not be installed to the local .m2 maven repo with mvn install nor will it be uploaded to e.g. Nexus during mvn deploy.
Other plugins like maven-assembly seem to register their e.g. jar-with-dependencies.jar artifact automatically. For capsule one can make things work when adding the following to the pom.xml:
```
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>build-helper-maven-plugin</artifactId>
  <version>1.7</version>
  <executions>
    <execution>
      <id>attach-artifacts</id>
      <phase>package</phase>
      <goals>
        <goal>attach-artifact</goal>
      </goals>
      <configuration>
        <artifacts>
          <artifact>
            <file>${project.build.directory}/${project.artifactId}-${project.version}-capsule-fat.jar</file>
            <type>jar</type>
            <classifier>capsule-fat</classifier>
          </artifact>
        </artifacts>
      </configuration>
    </execution>
  </executions>
</plugin>
```
It would be great to either have the artifacts registered automatically thru the capsule plugin or add this snippet to the documentation to relief other users from searching stackoverflow.

**Comment by tngmech** [comment]
Moved from https://github.com/puniverse/capsule-maven/issues/6 - may close the duplicate.

**Comment by chrischristo** [comment]
Ok good idea, with [0.10.5](https://github.com/chrischristo/capsule-maven-plugin/releases/tag/capsule-maven-plugin-0.10.5), you can just add `<goal>install</goal>` and it will install as desired. See [here](https://github.com/chrischristo/capsule-maven-plugin#capsule-goals) and [here](https://github.com/chrischristo/capsule-maven-plugin#building-automatically). I replicated what the attach-artifact goal (above) does.

**Comment by guwi17** [comment]
I reviewed the changes. Don't you think it's better to use the [MavenProjectHelper.attachArtifact(...)](https://maven.apache.org/ref/3.3.1/maven-core/apidocs/org/apache/maven/project/MavenProjectHelper.html#attachArtifact(org.apache.maven.project.MavenProject,%20java.lang.String,%20java.lang.String,%20java.io.File)) method to announce the generated JARs to Maven? This way Maven handles "install" and "deploy" automatically and we could add a classifier like "capsule-fat" or "with-dependencies".

**Comment by chrischristo** [comment]
Ah *sigh* wish I had known about that method. Will update for 0.10.6. For now 0.10.5 supports install only.

**Comment by chrischristo** [comment]
[Done](https://github.com/chrischristo/capsule-maven-plugin/releases/tag/capsule-maven-plugin-0.10.6)

**Comment by guwi17** [comment]
verified: 0.10.6 installs and deploys the artifact as expected.
```XML
      <plugin>
        <groupId>com.github.chrischristo</groupId>
        <artifactId>capsule-maven-plugin</artifactId>
        <version>${capsule.maven.plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
            </goals>
            <configuration>
              <types>fat</types>
              <appClass>simulator.SimulatorCli</appClass>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

**Comment by chrischristo** [comment]
Great! will close :)
