### ISSUE TITLE
Thin/empty (i.e. Maven) capsules not working with Capsule 1.0-RC2 and 1.0

### ISSUE THREAD

**Issue by circlespainter** [chrischristo/capsule-maven-plugin#25]
It looks like `MavenCaplet` (with its JAR content) is not being included. Tried with `0.10.7-SNAPSHOT` installed locally. Sample project: https://github.com/circlespainter/capsule-1.0-sample

**Comment by chrischristo** [comment]
Hi @circlespainter, yeah I realised that today too. Didn't see that the Capsule separated out the maven code into the capsule-maven caplet.

**Comment by chrischristo** [comment]
[fixed - 0.10.7](https://github.com/chrischristo/capsule-maven-plugin/releases/tag/capsule-maven-plugin-0.10.7)

I also tested against your sample project.
