### ISSUE TITLE
Minimum requirements (Maven)

### ISSUE THREAD

**Issue by khmarbaise** [chrischristo/capsule-maven-plugin#37]
I have read the requirement maven 3.1.+ but the code looks like 3.0.X would be ok...but the pom states the dependency to maven-project uses 3.0-alpha-2, maven-plugin-api uses 3.2.2..the question is why not using consistently version 3.0 ? Any special reason for this?

If you like to force using a particular maven version this should be done by using maven-enforcer-pugin?

**Comment by chrischristo** [comment]
Ok will look into this.

**Comment by chrischristo** [comment]
The requirements for 3.1.x + is because we use the eclipse Aether [see here](https://github.com/chrischristo/capsule-maven-plugin/issues/4).

For the versions for maven plugins, we aim to use the latest. Currently this is:

```
<maven.compiler.plugin.version>3.3</maven.compiler.plugin.version>
<maven.project.version>3.0-alpha-2</maven.project.version>
<maven.plugin.plugin.version>3.4</maven.plugin.plugin.version>
<maven.plugin.api.version>3.3.9</maven.plugin.api.version>
<maven.plugin.annotations.version>3.4</maven.plugin.annotations.version>
```

This works fine with maven version 3.1.x+ as stated in the documentation.
