### ISSUE TITLE
How to specify capsule-daemon?

### ISSUE THREAD

**Issue by gitblit** [chrischristo/capsule-maven-plugin#38]
I see the `<caplets>` tag but it's unclear how to specify `capsule-daemon`, for example.  Do I add that as a compile dependency to my app?

**Comment by gitblit** [comment]
Adding `capsule-daemon` as a `compile` dependency did not work.

**Comment by chrischristo** [comment]
If the class is a local caplet then yes you can do `<caplets>MyCaplet</caplets>`. However, if you want to use a caplet that's not a local class (i.e get it from a dependency) you need to have the full coordinates:

`<caplets>co.paralleluniverse:capsule-daemon:0.1.0</caplets>`

And you also need to include it as a dependency:

```
<dependency>
	<groupId>co.paralleluniverse</groupId>
	<artifactId>capsule-daemon</artifactId>
	<version>0.1.0</version>
</dependency>
```

And if you want to use multiple caplets, you can mix local and non-local caplets too: 

`<caplets>MyCapsule co.paralleluniverse:capsule-daemon:0.1.0</caplets>`

**However, there is a bug at the moment, see please release of next version.**

**Comment by chrischristo** [comment]
[Fixed](https://github.com/chrischristo/capsule-maven-plugin/releases/tag/capsule-maven-plugin-1.0.2)
