### ISSUE TITLE
Update to Capsule 1.0.1

### ISSUE THREAD

**Issue by gitblit** [chrischristo/capsule-maven-plugin#39]
It looks like this plugin depends on 1.0.0 but in October puniverse issued a point release with some fixes that may be important.  Currently I'm using the `<capsule.version>` properties trick, but maybe it's a good idea to update the dependency.

**Comment by chrischristo** [comment]
Ah whoops the plugin version 1.0.1 was supposed to default to Capsule 1.0.1, forgot to change that! So yeah it currently defaults to Capsule 1.0.

I'll fix it in 1.0.2 of the plugin. In the mean time yeah you'll have to manually set `<capsule.version>1.0.1</capsule.version>`

**Comment by chrischristo** [comment]
[Fixed](https://github.com/chrischristo/capsule-maven-plugin/releases/tag/capsule-maven-plugin-1.0.2).
