### ISSUE TITLE
Support for mirrors

### ISSUE THREAD

**Issue by balbusm** [chrischristo/capsule-maven-plugin#42]
I'm trying to create fat jar for multiproject capsule as described in #28.
However in my organization access to maven central is restricted. We are using mirrors. 
My settings.xml defines mirrors:
```
<mirrors>
  <mirror>
    <id>nexus</id>
    <mirrorOf>*</mirrorOf>
    <url>MY_ORGANIZATION_MIRROR</url>
  </mirror>
</mirrors>
````
The problem is that fat jar doesn't contain Repository tag as thin jar.
Could you change the code that Repository tag is automatically added for fat jar too?

**Comment by chrischristo** [comment]
ah yep good catch!

**Comment by chrischristo** [comment]
[see here](https://github.com/chrischristo/capsule-maven-plugin/releases/tag/capsule-maven-plugin-1.0.4)

**Comment by balbusm** [comment]
Works great!
