### ISSUE TITLE
Add classifier support

### ISSUE THREAD

**Issue by balbusm** [chrischristo/capsule-maven-plugin#43]
Classifier is ignored for dependencies. It is not added to the manifest file.
As far as I see the following pattern works:
`groupId:artifactId:version:classifier`

**Comment by chrischristo** [comment]
Classifier support should be supported in [latest version 1.2.0](https://github.com/chrischristo/capsule-maven-plugin/releases/tag/capsule-maven-plugin-1.2.0).
