### ISSUE TITLE
Capsule maven latest plugin build fail 

### ISSUE THREAD

**Issue by bwzhang2011** [chrischristo/capsule-maven-plugin#46]
Hi, I encountered some problem while building with capsule maven plugin since upgrading from 0.10.8 to the latest one. here came the stack trace as follows:
![image](https://cloud.githubusercontent.com/assets/749788/13592602/b49bbda6-e52e-11e5-8543-de933886b4fb.png)

what's more, my configuration with capsule was like this, please help me if I were wrong with such:

			<plugin>
				<groupId>com.github.chrischristo</groupId>
				<artifactId>capsule-maven-plugin</artifactId>
				<version>${capsule.maven.plugin.version}</version>
				<configuration>
					
					<appClass>com.mama100.platform.test.rocetmqdemo.RocketMQDemoMain</appClass>
					
					<trampoline>true</trampoline>
					
					<types>fat</types>
					<customDescriptorFat>-all</customDescriptorFat>
					
					<manifest>
						<entry>
							<key>Min-Java-Version</key>
							<value>1.7.0</value>
						</entry>
						<entry>
							<key>BuildBy</key>
							<value>bwzhang</value>
						</entry>
					</manifest>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>build</goal>
						</goals>
					</execution>
				</executions>
	</plugin>

**Comment by bwzhang2011** [comment]
@chrischristo, any update with such issue ?

**Comment by chrischristo** [comment]
looking into this

**Comment by chrischristo** [comment]
Ah this is due to the plugin trying to use the ```chmod``` command which it needs in order to create the executable files (from marking ```<chmod>true</chmod>``` or ```<trampoline>true</trampoline>```). This command is typically only available on unix systems (Mac, Linux etc). On Windows one would need to have something like Cygwin installed. I've managed to create a workaround so Windows users wouldn't need this. Await next release for this.

**Comment by bwzhang2011** [comment]
@chrischristo, thanks for feed back and hope such could be provided not long in the future.

**Comment by chrischristo** [comment]
See [v1.0.5](https://github.com/chrischristo/capsule-maven-plugin/releases/tag/capsule-maven-plugin-1.0.5)

**Comment by bwzhang2011** [comment]
@chrischristo, thanks a lot for your great work and I will try it afterwards.
