### ISSUE TITLE
Document specifying separately `capsule`'s and `capsule-maven`'s versions

### ISSUE THREAD

**Issue by circlespainter** [chrischristo/capsule-maven-plugin#49]
In the future `capsule` and `capsule-maven` could be released separately as they are now two different projects, so users may want to specify different versions for them.

**Comment by chrischristo** [comment]
You can already set the capsule maven version in the plugin.

The plugin looks for two variables defined in the pom.xml:

```
<capsule.version>1.0.2</capsule.version>
<capsule.maven.version>1.0.3-SNAPSHOT</capsule.maven.version>
```

This was done in a recent release, so please check you're using the [latest version of the plugin](https://github.com/chrischristo/capsule-maven-plugin/releases).

Alas its not stated in the README, I'll update it.

**Comment by circlespainter** [comment]
Thanks, I've updated the title to reflect that.

**Comment by chrischristo** [comment]
[See Quick Start](https://github.com/chrischristo/capsule-maven-plugin#quick-start).
